apiVersion: v1
name: devops
version: 1.1.3
namespace: kubesphere-devops-system
displayName:
  zh: DevOps
  en: DevOps
description:
  zh: |-
    KubeSphere DevOps 提供端到端的工作流，集成主流 CI/CD 工具，帮助不同的组织加快产品上市时间。
  en: |-
    KubeSphere DevOps offers an end-to-end workflow, integrating mainstream CI/CD tools, and helps organizations accelerate the time to market for products.
keywords:
  - DevOps
  - CI/CD
  - Integration & Delivery
home: https://kubesphere.com.cn/
category: integration-delivery
sources: []
kubeVersion: '>=1.19.0-0'
ksVersion: '>=4.1.2-0'
provider:
  zh:
    name: 北京青云科技股份有限公司
    email: kubesphere@yunify.com
    url: https://kubesphere.com.cn/
  en:
    name: QingCloud Technologies
    email: kubesphere@yunify.com
    url: https://kubesphere.co/
maintainers:
  - name: KubeSphere
    email: kubesphere@yunify.com
staticFileDirectory: static
icon: ./static/devops-icon.png
installationMode: Multicluster
dependencies:
  - name: extension
    tags:
      - extension
  - name: agent
    tags:
      - agent
images:
  - registry.cn-beijing.aliyuncs.com/kubesphereon/devops-apiserver:v4.1.3
  - registry.cn-beijing.aliyuncs.com/kubesphereon/devops-controller:v4.1.3
  - registry.cn-beijing.aliyuncs.com/kubesphereon/devops-tools:v4.1.3
  - registry.cn-beijing.aliyuncs.com/kubesphereon/devops-jenkins:v4.1.2-2.346.3
  - registry.cn-beijing.aliyuncs.com/kubesphereon/inbound-agent:4.10-2
  - registry.cn-beijing.aliyuncs.com/kubesphereon/builder-base:v4.1.3
  - registry.cn-beijing.aliyuncs.com/kubesphereon/builder-nodejs:v3.2.0
  - registry.cn-beijing.aliyuncs.com/kubesphereon/builder-maven:v3.2.0
  - registry.cn-beijing.aliyuncs.com/kubesphereon/builder-maven:v3.2.1-jdk11
  - registry.cn-beijing.aliyuncs.com/kubesphereon/builder-python:v3.2.0
  - registry.cn-beijing.aliyuncs.com/kubesphereon/builder-go:v3.2.0
  - registry.cn-beijing.aliyuncs.com/kubesphereon/builder-go:v3.2.2-1.16
  - registry.cn-beijing.aliyuncs.com/kubesphereon/builder-go:v3.2.2-1.17
  - registry.cn-beijing.aliyuncs.com/kubesphereon/builder-go:v3.2.2-1.18
  - registry.cn-beijing.aliyuncs.com/kubesphereon/builder-base:v4.1.3-podman
  - registry.cn-beijing.aliyuncs.com/kubesphereon/builder-nodejs:v3.2.0-podman
  - registry.cn-beijing.aliyuncs.com/kubesphereon/builder-maven:v3.2.0-podman
  - registry.cn-beijing.aliyuncs.com/kubesphereon/builder-maven:v3.2.1-jdk11-podman
  - registry.cn-beijing.aliyuncs.com/kubesphereon/builder-python:v3.2.0-podman
  - registry.cn-beijing.aliyuncs.com/kubesphereon/builder-go:v3.2.0-podman
  - registry.cn-beijing.aliyuncs.com/kubesphereon/builder-go:v3.2.2-1.16-podman
  - registry.cn-beijing.aliyuncs.com/kubesphereon/builder-go:v3.2.2-1.17-podman
  - registry.cn-beijing.aliyuncs.com/kubesphereon/builder-go:v3.2.2-1.18-podman
  - registry.cn-beijing.aliyuncs.com/kubesphereon/argocd:v2.3.3
  - registry.cn-beijing.aliyuncs.com/kubesphereon/argocd-applicationset:v0.4.1
  - registry.cn-beijing.aliyuncs.com/kubesphereon/dex:v2.30.2
  - registry.cn-beijing.aliyuncs.com/kubesphereon/redis:6.2.6-alpine
docs: https://docs.kubesphere.com.cn/
