global:
  imageRegistry: dockerhub.kubekey.local
  imagePullSecrets: []
  tag:

kubeedge:
  enabled: true
cloudcore:
  cloudCore:
    modules:
      cloudHub:
        advertiseAddress:
          - ""
