global:
  imageRegistry: registry.cn-beijing.aliyuncs.com
  imagePullSecrets: []
  tag:

kubeedge:
  enabled: true
cloudcore:
  cloudCore:
    modules:
      cloudHub:
        advertiseAddress:
          - ""
