apiVersion: v1
appVersion: 0.2.0
description: Backend of kubesphere gateway extension.
home: https://kubesphere.io
name: backend
sources:
- https://github.com/kubesphere-extensions/gateway
type: application
version: 0.2.0
