{{- /*
Do not change in-place! In order to change this file first read following link:
https://github.com/WhizardTelemetry/WhizardAlerting/tree/main/charts/whizard-alerting/hack
*/ -}}
{{- define "whizard-alerting.builtinRules.groups.thanos-rule.tmpl" }}

{{- $ruleTargetNamespace := printf "%s|%s" .Values.builtinRules.prometheusStackTarget.namespace (include "extension.namespace" .) }}
apiVersion: alerting.kubesphere.io/v2beta1
kind: GlobalRuleGroup
metadata:
  {{- if .Values.builtinRules.heritageNameOverride }}
  name: thanos-rule
  {{- else }}
  name: {{ printf "%s-%s" (include "extension.fullname" .) "thanos-rule" | trunc 63 | trimSuffix "-" }}
  {{- end }}
  labels:
    alerting.kubesphere.io/builtin: "true"
    alerting.kubesphere.io/enable: "true"
{{- if .Values.builtinRules.labels }}
{{ toYaml .Values.builtinRules.labels | indent 4 }}
{{- end }}
  annotations:
{{- if .Values.builtinRules.annotations }}
{{ toYaml .Values.builtinRules.annotations | indent 4 }}
{{- end }}
spec:
  rules:
{{- if not (.Values.builtinRules.disabled.ThanosRuleQueueIsDroppingAlerts | default false) }}
  - alert: ThanosRuleQueueIsDroppingAlerts
    annotations:
{{- if .Values.builtinRules.additionalRuleAnnotations }}
{{ toYaml .Values.builtinRules.additionalRuleAnnotations | indent 6 }}
{{- end }}
      description: Thanos Rule {{`{{`}}$labels.instance{{`}}`}} in {{`{{`}}$labels.cluster{{`}}`}}/{{`{{`}}$labels.namespace{{`}}`}} is failing to queue alerts.
      runbook_url: {{ trimAll "/" .Values.builtinRules.runbookUrl }}/thanos/thanosrulequeueisdroppingalerts
      summary: Thanos Rule is failing to queue alerts.
    expr: sum by (cluster, namespace, job, instance) (rate(thanos_alert_queue_alerts_dropped_total{job=~".*(thanos-rule|ruler-whizard).*", namespace=~"{{ $ruleTargetNamespace }}"}[5m])) > 0
    for: 5m
    id: 8a663511d4642025f5a0580fd618d89b
    labels:
{{- if .Values.builtinRules.additionalRuleLabels }}
{{ toYaml .Values.builtinRules.additionalRuleLabels | indent 6 }}
{{- end }}
    severity: critical
{{- end }}
{{- if not (.Values.builtinRules.disabled.ThanosRuleSenderIsFailingAlerts | default false) }}
  - alert: ThanosRuleSenderIsFailingAlerts
    annotations:
{{- if .Values.builtinRules.additionalRuleAnnotations }}
{{ toYaml .Values.builtinRules.additionalRuleAnnotations | indent 6 }}
{{- end }}
      description: Thanos Rule {{`{{`}}$labels.instance{{`}}`}} in {{`{{`}}$labels.cluster{{`}}`}}/{{`{{`}}$labels.namespace{{`}}`}} is failing to send alerts to alertmanager.
      runbook_url: {{ trimAll "/" .Values.builtinRules.runbookUrl }}/thanos/thanosrulesenderisfailingalerts
      summary: Thanos Rule is failing to send alerts to alertmanager.
    expr: sum by (cluster, namespace, job, instance) (rate(thanos_alert_sender_alerts_dropped_total{job=~".*(thanos-rule|ruler-whizard).*", namespace=~"{{ $ruleTargetNamespace }}"}[5m])) > 0
    for: 5m
    id: 7e994d7a9912689118fe68327d516d74
    labels:
{{- if .Values.builtinRules.additionalRuleLabels }}
{{ toYaml .Values.builtinRules.additionalRuleLabels | indent 6 }}
{{- end }}
    severity: critical
{{- end }}
{{- if not (.Values.builtinRules.disabled.ThanosRuleHighRuleEvaluationFailures | default false) }}
  - alert: ThanosRuleHighRuleEvaluationFailures
    annotations:
{{- if .Values.builtinRules.additionalRuleAnnotations }}
{{ toYaml .Values.builtinRules.additionalRuleAnnotations | indent 6 }}
{{- end }}
      description: Thanos Rule {{`{{`}}$labels.instance{{`}}`}} in {{`{{`}}$labels.cluster{{`}}`}}/{{`{{`}}$labels.namespace{{`}}`}} is failing to evaluate rules.
      runbook_url: {{ trimAll "/" .Values.builtinRules.runbookUrl }}/thanos/thanosrulehighruleevaluationfailures
      summary: Thanos Rule is failing to evaluate rules.
    expr: |-
      (
        sum by (cluster, namespace, job, instance) (rate(prometheus_rule_evaluation_failures_total{job=~".*(thanos-rule|ruler-whizard).*", namespace=~"{{ $ruleTargetNamespace }}"}[5m]))
      /
        sum by (cluster, namespace, job, instance) (rate(prometheus_rule_evaluations_total{job=~".*(thanos-rule|ruler-whizard).*", namespace=~"{{ $ruleTargetNamespace }}"}[5m]))
      * 100 > 5
      )
    for: 5m
    id: 1369506100b9d16e1ee4c5369b07eb4d
    labels:
{{- if .Values.builtinRules.additionalRuleLabels }}
{{ toYaml .Values.builtinRules.additionalRuleLabels | indent 6 }}
{{- end }}
    severity: critical
{{- end }}
{{- if not (.Values.builtinRules.disabled.ThanosRuleHighRuleEvaluationWarnings | default false) }}
  - alert: ThanosRuleHighRuleEvaluationWarnings
    annotations:
{{- if .Values.builtinRules.additionalRuleAnnotations }}
{{ toYaml .Values.builtinRules.additionalRuleAnnotations | indent 6 }}
{{- end }}
      description: Thanos Rule {{`{{`}}$labels.instance{{`}}`}} in {{`{{`}}$labels.cluster{{`}}`}}/{{`{{`}}$labels.namespace{{`}}`}} has high number of evaluation warnings.
      runbook_url: {{ trimAll "/" .Values.builtinRules.runbookUrl }}/thanos/thanosrulehighruleevaluationwarnings
      summary: Thanos Rule has high number of evaluation warnings.
    expr: sum by (cluster, namespace, job, instance) (rate(thanos_rule_evaluation_with_warnings_total{job=~".*(thanos-rule|ruler-whizard).*", namespace=~"{{ $ruleTargetNamespace }}"}[5m])) > 0
    for: 15m
    id: e86609a38691ffe545d2a8da6743dfab
    labels:
{{- if .Values.builtinRules.additionalRuleLabels }}
{{ toYaml .Values.builtinRules.additionalRuleLabels | indent 6 }}
{{- end }}
    severity: info
{{- end }}
{{- if not (.Values.builtinRules.disabled.ThanosRuleRuleEvaluationLatencyHigh | default false) }}
  - alert: ThanosRuleRuleEvaluationLatencyHigh
    annotations:
{{- if .Values.builtinRules.additionalRuleAnnotations }}
{{ toYaml .Values.builtinRules.additionalRuleAnnotations | indent 6 }}
{{- end }}
      description: Thanos Rule {{`{{`}}$labels.instance{{`}}`}} in {{`{{`}}$labels.cluster{{`}}`}}/{{`{{`}}$labels.namespace{{`}}`}} has higher evaluation latency than interval for {{`{{`}}$labels.rule_group{{`}}`}}.
      runbook_url: {{ trimAll "/" .Values.builtinRules.runbookUrl }}/thanos/thanosruleruleevaluationlatencyhigh
      summary: Thanos Rule has high rule evaluation latency.
    expr: |-
      (
        sum by (cluster, namespace, job, instance, rule_group) (prometheus_rule_group_last_duration_seconds{job=~".*(thanos-rule|ruler-whizard).*", namespace=~"{{ $ruleTargetNamespace }}"})
      >
        sum by (cluster, namespace, job, instance, rule_group) (prometheus_rule_group_interval_seconds{job=~".*(thanos-rule|ruler-whizard).*", namespace=~"{{ $ruleTargetNamespace }}"})
      )
    for: 5m
    id: 386d20888c0984a7a5640e1627c3fb99
    labels:
{{- if .Values.builtinRules.additionalRuleLabels }}
{{ toYaml .Values.builtinRules.additionalRuleLabels | indent 6 }}
{{- end }}
    severity: warning
{{- end }}
{{- if not (.Values.builtinRules.disabled.ThanosRuleGrpcErrorRate | default false) }}
  - alert: ThanosRuleGrpcErrorRate
    annotations:
{{- if .Values.builtinRules.additionalRuleAnnotations }}
{{ toYaml .Values.builtinRules.additionalRuleAnnotations | indent 6 }}
{{- end }}
      description: Thanos Rule {{`{{`}}$labels.job{{`}}`}} in {{`{{`}}$labels.cluster{{`}}`}}/{{`{{`}}$labels.namespace{{`}}`}} is failing to handle {{`{{`}}$value | humanize{{`}}`}}% of requests.
      runbook_url: {{ trimAll "/" .Values.builtinRules.runbookUrl }}/thanos/thanosrulegrpcerrorrate
      summary: Thanos Rule is failing to handle grpc requests.
    expr: |-
      (
        sum by (cluster, namespace, job, instance) (rate(grpc_server_handled_total{grpc_code=~"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss|DeadlineExceeded", job=~".*(thanos-rule|ruler-whizard).*", namespace=~"{{ $ruleTargetNamespace }}"}[5m]))
      /
        sum by (cluster, namespace, job, instance) (rate(grpc_server_started_total{job=~".*(thanos-rule|ruler-whizard).*", namespace=~"{{ $ruleTargetNamespace }}"}[5m]))
      * 100 > 5
      )
    for: 5m
    id: 6cefe8c838cd7b1b9fc8ac3a67e7fed6
    labels:
{{- if .Values.builtinRules.additionalRuleLabels }}
{{ toYaml .Values.builtinRules.additionalRuleLabels | indent 6 }}
{{- end }}
    severity: warning
{{- end }}
{{- if not (.Values.builtinRules.disabled.ThanosRuleConfigReloadFailure | default false) }}
  - alert: ThanosRuleConfigReloadFailure
    annotations:
{{- if .Values.builtinRules.additionalRuleAnnotations }}
{{ toYaml .Values.builtinRules.additionalRuleAnnotations | indent 6 }}
{{- end }}
      description: Thanos Rule {{`{{`}}$labels.job{{`}}`}} in {{`{{`}}$labels.cluster{{`}}`}}/{{`{{`}}$labels.namespace{{`}}`}} has not been able to reload its configuration.
      runbook_url: {{ trimAll "/" .Values.builtinRules.runbookUrl }}/thanos/thanosruleconfigreloadfailure
      summary: Thanos Rule has not been able to reload configuration.
    expr: avg by (cluster, namespace, job, instance) (thanos_rule_config_last_reload_successful{job=~".*(thanos-rule|ruler-whizard).*", namespace=~"{{ $ruleTargetNamespace }}"}) != 1
    for: 5m
    id: 71de0adaceee2af75a09beb08a0062a2
    labels:
{{- if .Values.builtinRules.additionalRuleLabels }}
{{ toYaml .Values.builtinRules.additionalRuleLabels | indent 6 }}
{{- end }}
    severity: info
{{- end }}
{{- if not (.Values.builtinRules.disabled.ThanosRuleQueryHighDNSFailures | default false) }}
  - alert: ThanosRuleQueryHighDNSFailures
    annotations:
{{- if .Values.builtinRules.additionalRuleAnnotations }}
{{ toYaml .Values.builtinRules.additionalRuleAnnotations | indent 6 }}
{{- end }}
      description: Thanos Rule {{`{{`}}$labels.job{{`}}`}} in {{`{{`}}$labels.cluster{{`}}`}}/{{`{{`}}$labels.namespace{{`}}`}} has {{`{{`}}$value | humanize{{`}}`}}% of failing DNS queries for query endpoints.
      runbook_url: {{ trimAll "/" .Values.builtinRules.runbookUrl }}/thanos/thanosrulequeryhighdnsfailures
      summary: Thanos Rule is having high number of DNS failures.
    expr: |-
      (
        sum by (cluster, namespace, job, instance) (rate(thanos_rule_query_apis_dns_failures_total{job=~".*(thanos-rule|ruler-whizard).*", namespace=~"{{ $ruleTargetNamespace }}"}[5m]))
      /
        sum by (cluster, namespace, job, instance) (rate(thanos_rule_query_apis_dns_lookups_total{job=~".*(thanos-rule|ruler-whizard).*", namespace=~"{{ $ruleTargetNamespace }}"}[5m]))
      * 100 > 1
      )
    for: 15m
    id: 70d976940a6ee03ab86a658abf3a0c08
    labels:
{{- if .Values.builtinRules.additionalRuleLabels }}
{{ toYaml .Values.builtinRules.additionalRuleLabels | indent 6 }}
{{- end }}
    severity: warning
{{- end }}
{{- if not (.Values.builtinRules.disabled.ThanosRuleAlertmanagerHighDNSFailures | default false) }}
  - alert: ThanosRuleAlertmanagerHighDNSFailures
    annotations:
{{- if .Values.builtinRules.additionalRuleAnnotations }}
{{ toYaml .Values.builtinRules.additionalRuleAnnotations | indent 6 }}
{{- end }}
      description: Thanos Rule {{`{{`}}$labels.instance{{`}}`}} in {{`{{`}}$labels.cluster{{`}}`}}/{{`{{`}}$labels.namespace{{`}}`}} has {{`{{`}}$value | humanize{{`}}`}}% of failing DNS queries for Alertmanager endpoints.
      runbook_url: {{ trimAll "/" .Values.builtinRules.runbookUrl }}/thanos/thanosrulealertmanagerhighdnsfailures
      summary: Thanos Rule is having high number of DNS failures.
    expr: |-
      (
        sum by (cluster, namespace, job, instance) (rate(thanos_rule_alertmanagers_dns_failures_total{job=~".*(thanos-rule|ruler-whizard).*", namespace=~"{{ $ruleTargetNamespace }}"}[5m]))
      /
        sum by (cluster, namespace, job, instance) (rate(thanos_rule_alertmanagers_dns_lookups_total{job=~".*(thanos-rule|ruler-whizard).*", namespace=~"{{ $ruleTargetNamespace }}"}[5m]))
      * 100 > 1
      )
    for: 15m
    id: 8cbe90cf6e5abac46fa60f29b9b3dc12
    labels:
{{- if .Values.builtinRules.additionalRuleLabels }}
{{ toYaml .Values.builtinRules.additionalRuleLabels | indent 6 }}
{{- end }}
    severity: warning
{{- end }}
{{- if not (.Values.builtinRules.disabled.ThanosRuleNoEvaluationFor10Intervals | default false) }}
  - alert: ThanosRuleNoEvaluationFor10Intervals
    annotations:
{{- if .Values.builtinRules.additionalRuleAnnotations }}
{{ toYaml .Values.builtinRules.additionalRuleAnnotations | indent 6 }}
{{- end }}
      description: Thanos Rule {{`{{`}}$labels.job{{`}}`}} in {{`{{`}}$labels.cluster{{`}}`}}/{{`{{`}}$labels.namespace{{`}}`}} has rule groups that did not evaluate for at least 10x of their expected interval.
      runbook_url: {{ trimAll "/" .Values.builtinRules.runbookUrl }}/thanos/thanosrulenoevaluationfor10intervals
      summary: Thanos Rule has rule groups that did not evaluate for 10 intervals.
    expr: |-
      time() -  max by (cluster, namespace, job, instance, group) (prometheus_rule_group_last_evaluation_timestamp_seconds{job=~".*(thanos-rule|ruler-whizard).*", namespace=~"{{ $ruleTargetNamespace }}"})
      >
      10 * max by (cluster, namespace, job, instance, group) (prometheus_rule_group_interval_seconds{job=~".*(thanos-rule|ruler-whizard).*", namespace=~"{{ $ruleTargetNamespace }}"})
    for: 5m
    id: 96e6fa0bcbecd8b9c2720a168bb9ae68
    labels:
{{- if .Values.builtinRules.additionalRuleLabels }}
{{ toYaml .Values.builtinRules.additionalRuleLabels | indent 6 }}
{{- end }}
    severity: info
{{- end }}
{{- if not (.Values.builtinRules.disabled.ThanosNoRuleEvaluations | default false) }}
  - alert: ThanosNoRuleEvaluations
    annotations:
{{- if .Values.builtinRules.additionalRuleAnnotations }}
{{ toYaml .Values.builtinRules.additionalRuleAnnotations | indent 6 }}
{{- end }}
      description: Thanos Rule {{`{{`}}$labels.instance{{`}}`}} in {{`{{`}}$labels.cluster{{`}}`}}/{{`{{`}}$labels.namespace{{`}}`}} did not perform any rule evaluations in the past 10 minutes.
      runbook_url: {{ trimAll "/" .Values.builtinRules.runbookUrl }}/thanos/thanosnoruleevaluations
      summary: Thanos Rule did not perform any rule evaluations.
    expr: |-
      sum by (cluster, namespace, job, instance) (rate(prometheus_rule_evaluations_total{job=~".*(thanos-rule|ruler-whizard).*", namespace=~"{{ $ruleTargetNamespace }}"}[5m])) <= 0
        and
      sum by (cluster, namespace, job, instance) (thanos_rule_loaded_rules{job=~".*(thanos-rule|ruler-whizard).*", namespace=~"{{ $ruleTargetNamespace }}"}) > 0
    for: 5m
    id: 8aa44c144c2a9504e9905d445136dcdb
    labels:
{{- if .Values.builtinRules.additionalRuleLabels }}
{{ toYaml .Values.builtinRules.additionalRuleLabels | indent 6 }}
{{- end }}
    severity: critical
{{- end }}
{{- end }}