global:
  imageRegistry: "registry.cn-beijing.aliyuncs.com"
  imagePullSecrets: []

metricsServer:
  enabled: true

metrics-server:
  fullnameOverride: "metrics-server"

  image:
    registry: registry.cn-beijing.aliyuncs.com
    repository: kubesphereon/metrics-server
    tag: "v0.7.0"

  args:
  - --kubelet-insecure-tls

  # See https://github.com/kubernetes-sigs/metrics-server#scaling
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      cpu: 100m
      memory: 200Mi

  addonResizer:
    enabled: false
    image:
      registry: docker
      repository: kubesphereon/addon-resizer
      tag: 1.8.20