{{- if .Values.crds.update }}
{{- $crdFiles := .Files.Glob "crds/**" }}
{{- $i := 0 }}
{{- range $path, $_ := $crdFiles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "extension.fullname" $ }}-crds-{{ $i }}
  namespace: {{ include "extension.namespace" $ }}
  labels:
    {{- include "extension.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
data:
  {{ $path | base }}: |
    {{- $.Files.Get $path | nindent 4 }}
---
{{- $i = add1 $i }}
{{- end }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "extension.fullname" . }}-update-crds
  labels:
    {{- include "extension.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
  - apiGroups: 
    - apiextensions.k8s.io
    resources: 
    - customresourcedefinitions
    verbs:
    - get
    - create
    - update
    - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "extension.fullname" . }}-update-crds
  labels:
    {{- include "extension.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "extension.fullname" . }}-update-crds
subjects:
  - kind: ServiceAccount
    name: {{ include "extension.fullname" . }}-update-crds
    namespace: {{ include "extension.namespace" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "extension.fullname" . }}-update-crds
  labels:
    {{- include "extension.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "extension.fullname" . }}-update-crds
  namespace: {{ include "extension.namespace" . }}
  labels:
    {{- include "extension.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "extension.fullname" . }}-update-crds
      volumes:
        {{- $i = 0 }}
        {{- range $path, $_ := $crdFiles }}
        - name: crds-{{ $i }}
          configMap:
            name: {{ include "extension.fullname" $ }}-crds-{{ $i }}
            items:
            - key: {{ $path | base }}
              path: {{ $path | base }}
        {{- $i = add1 $i }}
        {{- end }}
      containers:
        - name: update-crds
          image:  {{ template "extension.kubectl.image" . }}
          command:
            - /bin/bash
            - -c
            - |
              kubectl apply -f /data/crds 2>&1
          {{- $i = 0 }}
          volumeMounts:
          {{- range $path, $_ := $crdFiles }}
            - name: crds-{{ $i }}
              mountPath: /data/crds/{{ $path | base }}
              subPath: {{ $path | base }}
          {{- $i = add1 $i }}
          {{- end }}
          resources:
            {{- toYaml .Values.kubectl.resources | nindent 12 }}
{{- end }}