{{- $ca := genCA (printf "%s-ca" (include "extension.fullname" .)) 3650 }}
{{- $cn := printf "%s-admission-webhook" (include "extension.fullname" .) }}
{{- $altName1 := printf "%s.%s" (include "extension.fullname" .) (include "extension.namespace" .) }}
{{- $altName2 := printf "%s.%s.svc" (include "extension.fullname" .) (include "extension.namespace" .) }}
{{- $cert := genSignedCert $cn nil (list $altName1 $altName2) 3650 $ca }}

apiVersion: v1
data:
  ca.crt: {{ b64enc $ca.Cert | quote }}
  tls.crt: {{ b64enc  $cert.Cert | quote }}
  tls.key: {{ b64enc  $cert.Key | quote }}
kind: Secret
metadata:
  name: {{ include "extension.fullname" . }}-webhook-cert
  namespace: {{ include "extension.namespace" . }}
  labels:
    {{- include "extension.labels" . | nindent 4 }}
type: Opaque

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: rulegroups.alerting.kubesphere.io
  labels:
    {{- include "extension.labels" . | nindent 4 }}
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: {{ b64enc $ca.Cert | quote }}
      service:
        name: {{ include "extension.fullname" . }}
        namespace: {{ include "extension.namespace" . }}
        path: /validate-alerting-kubesphere-io-v2beta1-rulegroup
        port: 443
    failurePolicy: Ignore
    matchPolicy: Exact
    name: rulegroups.alerting.kubesphere.io
    namespaceSelector: {}
    objectSelector: {}
    rules:
      - apiGroups:
          - alerting.kubesphere.io
        apiVersions:
          - v2beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - rulegroups
        scope: '*'
    sideEffects: None
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: {{ b64enc $ca.Cert | quote }}
      service:
        name: {{ include "extension.fullname" . }}
        namespace: {{ include "extension.namespace" . }}
        path: /validate-alerting-kubesphere-io-v2beta1-clusterrulegroup
        port: 443
    failurePolicy: Ignore
    matchPolicy: Exact
    name: clusterrulegroups.alerting.kubesphere.io
    namespaceSelector: {}
    objectSelector: {}
    rules:
      - apiGroups:
          - alerting.kubesphere.io
        apiVersions:
          - v2beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - clusterrulegroups
        scope: '*'
    sideEffects: None
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: {{ b64enc $ca.Cert | quote }}
      service:
        name: {{ include "extension.fullname" . }}
        namespace: {{ include "extension.namespace" . }}
        path: /validate-alerting-kubesphere-io-v2beta1-globalrulegroup
        port: 443
    failurePolicy: Ignore
    matchPolicy: Exact
    name: globalrulegroups.alerting.kubesphere.io
    namespaceSelector: {}
    objectSelector: {}
    rules:
      - apiGroups:
          - alerting.kubesphere.io
        apiVersions:
          - v2beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - globalrulegroups
        scope: '*'
    sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: rulegroups.alerting.kubesphere.io
  labels:
    {{- include "extension.labels" . | nindent 4 }}
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: {{ b64enc $ca.Cert | quote }}
      service:
        name: {{ include "extension.fullname" . }}
        namespace: {{ include "extension.namespace" . }}
        path: /mutate-alerting-kubesphere-io-v2beta1-rulegroup
        port: 443
    failurePolicy: Ignore
    matchPolicy: Exact
    name: rulegroups.alerting.kubesphere.io
    namespaceSelector: {}
    objectSelector: {}
    rules:
      - apiGroups:
          - alerting.kubesphere.io
        apiVersions:
          - v2beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - rulegroups
        scope: '*'
    sideEffects: None
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: {{ b64enc $ca.Cert | quote }}
      service:
        name: {{ include "extension.fullname" . }}
        namespace: {{ include "extension.namespace" . }}
        path: /mutate-alerting-kubesphere-io-v2beta1-clusterrulegroup
        port: 443
    failurePolicy: Ignore
    matchPolicy: Exact
    name: clusterrulegroups.alerting.kubesphere.io
    namespaceSelector: {}
    objectSelector: {}
    rules:
      - apiGroups:
          - alerting.kubesphere.io
        apiVersions:
          - v2beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - clusterrulegroups
        scope: '*'
    sideEffects: None
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: {{ b64enc $ca.Cert | quote }}
      service:
        name: {{ include "extension.fullname" . }}
        namespace: {{ include "extension.namespace" . }}
        path: /mutate-alerting-kubesphere-io-v2beta1-globalrulegroup
        port: 443
    failurePolicy: Ignore
    matchPolicy: Exact
    name: globalrulegroups.alerting.kubesphere.io
    namespaceSelector: {}
    objectSelector: {}
    rules:
      - apiGroups:
          - alerting.kubesphere.io
        apiVersions:
          - v2beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - globalrulegroups
        scope: '*'
    sideEffects: None